# -*- coding: utf-8 -*-
"""typing speed tester.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aYdI2n7euAnfXY6rZiBD8gkQQaduHsUv
"""

import random
import time

def generate_random_text():
    # Replace this with a more extensive list of text passages.
    text = "This is a sample text for typing practice. Try to type it as fast and accurately as possible."
    words = text.split()
    return " ".join(random.sample(words, len(words)))

def calculate_wpm(correct_words, elapsed_time):
    words_per_minute = (correct_words / elapsed_time) * 60
    return words_per_minute

def typing_test():
    random_text = generate_random_text()
    print("Type the following text:")
    print(random_text)

    input_text = input()
    start_time = time.time()

    input_words = input_text.split()
    correct_words = sum(1 for a, b in zip(random_text.split(), input_words) if a == b)

    end_time = time.time()
    elapsed_time = end_time - start_time

    wpm = calculate_wpm(correct_words, elapsed_time)

    print(f"Your typing speed is {wpm:.2f} WPM.")

if __name__ == "__main__":
    typing_test()